repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools, types-click]
        files: ^snap7

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.2'
    hooks:
      - id: ruff
      - id: ruff-format
exclude: "snap7/protocol.py"
