name: 'prepare to build a package'
description: 'Downloads and unpacks snap7 archive. Copies the required files. Updates wheels'
inputs:
  snap7-archive-url:
    description: 'Link to download snap7 archive'
    required: true
    default: 'https://sourceforge.net/projects/snap7/files/1.4.2/snap7-full-1.4.2.7z/download'
runs:
  using: "composite"
  steps:
      - name: Cache snap7-archive
        id: snap7-archive
        uses: actions/cache@v3
        with:
          path: snap7-full-1.4.2.7z
          key: ${{ inputs.snap7-archive-url }}

      - name: Install choco packages
        if: steps.snap7-archive.outputs.cache-hit != 'true' && runner.os == 'Windows'
        shell: bash
        run: choco install --allow-downgrade wget --version 1.20.3.20190531

      - name: Get snap7
        if: steps.snap7-archive.outputs.cache-hit != 'true'
        shell: bash
        run: wget -O snap7-full-1.4.2.7z --content-disposition -c ${{ inputs.snap7-archive-url }}

      - name: Extract archive
        shell: bash
        run: 7z x snap7-full-1.4.2.7z

      - name: Update wheel
        shell: bash
        run: python3 -m pip install --upgrade pip wheel build
