name: Linux Test all Pythons
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Debian packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:gijzelaar/snap7
          sudo apt-get update -qq
          sudo apt-get install -y libsnap7-dev libsnap7-1
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[test]
      - name: Run pytest
        run: |
          which pytest
          pytest test/test_server.py test/test_client.py test/test_util.py test/test_mainloop.py
          sudo /opt/hostedtoolcache/Python/${{ matrix.python-version }}*/x64/bin/pytest test/test_partner.py
