name: pycodestyle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Debian packages
      run: |
        apt-get update -qq
        apt-get install -y python3-pip
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pycodestyle
    - name: Run pycodestyle
      run: pycodestyle snap7 test
